name: babysteps_app
description: A baby tracking and development app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  intl: ^0.18.1
  flutter_svg: ^2.0.5
  table_calendar: ^3.0.9
  fl_chart: ^0.62.0
  image_picker: ^0.8.7+5
  path_provider: ^2.0.15
  sqflite: ^2.2.8+4
  flutter_local_notifications: ^14.1.1
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^4.3.0
  http: ^0.13.6
  flutter_feather_icons: ^2.0.0+1
  flutter_spinkit: ^5.2.0
  carousel_slider: ^4.2.1
  flutter_markdown: ^0.6.15
  font_awesome_flutter: ^10.7.0
  confetti: ^0.7.0
  scrollable_positioned_list: ^0.3.8
  supabase_flutter: ^1.10.25
  uuid: ^4.2.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/
    - data/
    - .env
