WITH milestone_data (category, title, first_noticed_weeks, worry_after_weeks, activities) AS (
    VALUES
        ('Communication', 'Cries to express needs (hunger, discomfort, sleepiness)', 0, 2, ARRAY['Respond promptly to cries to build trust and communication.', 'Notice different cry patterns.', 'Soothe with a calm voice and gentle touch.']),
        ('Reflex/Feeding', 'Exhibits Rooting, Sucking, and Swallowing reflexes', 0, 2, ARRAY['Gently stroke their cheek to elicit the rooting reflex.', 'Ensure a calm feeding environment.', 'Allow non-nutritive sucking on a pacifier or clean finger for self-soothing.']),
        ('Reflex', 'Displays Moro (startle) reflex to loud noise or sudden movement', 0, 4, ARRAY['Swaddle your baby to help them feel secure and manage the startle reflex.', 'Use a calm voice to soothe them after a startle.', 'Avoid abrupt, loud noises when possible.']),
        ('Reflex/Motor', 'Grasps a finger when placed in palm (Palmar Grasp Reflex)', 0, 6, ARRAY['Gently place your clean finger or a soft, thin rattle in their palm to encourage this reflex.', 'Stroke the back of their hand to encourage them to open it.']),
        ('Sensory/Social', 'Recognizes caregiver''s scent and voice', 0, 4, ARRAY['Hold your baby skin-to-skin.', 'Talk and sing to them frequently in a soothing tone.', 'Maintain consistency in who provides care.']),
        ('Motor', 'Lifts head briefly during tummy time', 1, 6, ARRAY['Start with very short, supervised tummy time sessions (1-2 minutes) multiple times a day on your chest or a firm surface.']),
        ('Sensory', 'Focuses on objects 8-12 inches away (distance to your face)', 1, 5, ARRAY['Hold high-contrast (black and white) cards or your face at this distance.', 'Talk to them while making eye contact to encourage focus.']),
        ('Sensory', 'Turns head toward light sources', 2, 6, ARRAY['Place a soft, dim lamp to the side of their bassinet.', 'Notice how they turn towards a window with natural light.']),
        ('Social', 'Makes eye contact, especially during feeding', 2, 8, ARRAY['Hold your baby close during feedings.', 'Gaze into their eyes and smile gently.', 'Minimize distractions during this bonding time.']),
        ('Sensory', 'Begins to follow a slow-moving object to midline', 3, 8, ARRAY['Slowly move a high-contrast toy or your face from one side toward the center of their vision.']),
        ('Motor', 'Moves head from side to side when lying on stomach', 4, 8, ARRAY['During tummy time, make sounds or place toys slightly to one side to encourage them to turn their head.']),
        ('Communication', 'Begins to make cooing sounds (vowel sounds like ''ooh'' and ''aah'')', 5, 10, ARRAY['Imitate your baby''s coos and have back-and-forth “conversations.”', 'Talk to them throughout the day, narrating what you are doing.']),
        ('Motor', 'Pushes up on arms during tummy time', 7, 12, ARRAY['Increase tummy time duration as they get stronger.', 'Place a baby-safe mirror in front of them to motivate them to lift their head.']),
        ('Motor', 'Hands are more frequently open, less often in a fist', 8, 12, ARRAY['Gently massage their palms and stroke the back of their hands.', 'Offer soft toys of different textures for them to feel.']),
        ('Motor', 'Pushes up to elbows/forearms when on tummy', 10, 16, ARRAY['Use a rolled towel under their chest and armpits for support during tummy time.', 'Place engaging toys just within their sight.']),
        ('Motor', 'Brings hands to midline (together at their chest)', 11, 16, ARRAY['Lay your baby on their back and gently guide their hands together.', 'Sing songs with hand motions like “Pat-a-Cake.”']),
        ('Motor', 'Reaches for and swipes at dangling objects', 13, 20, ARRAY['Use a play gym with hanging toys.', 'Dangle a soft, colorful toy within their reach and encourage them to swipe at it.']),
        ('Motor', 'Holds head steady without support when held upright', 14, 20, ARRAY['Practice holding them in a supported sitting position on your lap.', 'Carry them in an upright position (facing you or outward) in a carrier.']),
        ('Motor', 'Rolls from tummy to back', 16, 24, ARRAY['During tummy time, if they push up high, they might roll over. Cheer them on!', 'Place toys to one side to encourage the weight shift that leads to a roll.']),
        ('Social', 'Copies some facial expressions, like smiling or frowning', 17, 24, ARRAY['Spend time face-to-face, making different expressions.', 'Play peek-a-boo.']),
        ('Cognitive/Motor', 'Puts things in their mouth to explore them', 18, 26, ARRAY['Provide a variety of safe, clean teething toys with different textures.', 'Ensure small objects are kept out of reach.']),
        ('Sensory', 'Turns to locate the source of a sound', 20, 26, ARRAY['Make gentle sounds with a rattle or your voice from different sides of the room.']),
        ('Social', 'Smiles spontaneously at people', 22, 28, ARRAY['Greet your baby with a big smile and enthusiastic voice when you enter the room.']),
        ('Motor', 'Begins to sit with support (propped with pillows or hands)', 23, 32, ARRAY['Use a Boppy pillow or surround them with cushions on the floor for short, supervised practice sessions.']),
        ('Fine Motor', 'Rakes objects with fingers', 25, 32, ARRAY['Place a few baby-safe puffs or a soft, small toy on their high chair tray and let them practice moving them.']),
        ('Cognitive', 'Shows curiosity about objects and tries to get things out of reach', 26, 34, ARRAY['Place an interesting toy just beyond their grasp to encourage them to stretch and move.']),
        ('Motor', 'Sits without support', 30, 38, ARRAY['Place toys in a circle around your baby to encourage them to twist and reach, building core strength and balance.']),
        ('Feeding/Motor', 'Begins to feed self finger foods (e.g., dissolvable puffs)', 31, 40, ARRAY['Offer soft, pea-sized pieces of food on their high chair tray.', 'Model picking up the food and eating it.']),
        ('Cognitive', 'Looks for objects they see you hide (beginning of object permanence)', 33, 42, ARRAY['Play a game where you hide a favorite toy under a small blanket, but leave part of it showing.', 'Cheer when they find it.']),
        ('Communication', 'Babbles with consonant sounds (e.g., “bababa,” “mamama”)', 34, 42, ARRAY['Respond to their babbles as if you''re having a conversation.', 'Read books with rhyming and repetitive sounds.']),
        ('Motor', 'Pulls to a standing position', 36, 48, ARRAY['Ensure you have sturdy, safe furniture (like a low coffee table) for them to use.', 'Place favorite toys on the couch to motivate them to pull up.']),
        ('Fine Motor', 'Uses pincer grasp (thumb and forefinger) to pick up small items', 38, 52, ARRAY['Offer small, safe snacks like O-shaped cereal for them to practice on.', 'Use puzzles with small knobs.']),
        ('Motor', 'Crawls or scoots', 39, 52, ARRAY['Create a safe, open space for them to explore.', 'Get on the floor and crawl with them to make it a game.']),
        ('Communication', 'Understands “no”', 40, 52, ARRAY['Use “no” firmly but calmly for safety issues.', 'Redirect their attention to a more appropriate activity.']),
        ('Motor', 'Walks holding onto furniture (“cruising”)', 42, 56, ARRAY['Arrange furniture to create a safe “cruising” path.', 'Encourage them to move between pieces of furniture that are a short distance apart.']),
        ('Communication', 'Waves “bye-bye”', 44, 56, ARRAY['Wave and say “bye-bye” every time someone leaves the house.', 'Sing songs that involve waving.']),
        ('Cognitive', 'Finds a completely hidden object', 45, 60, ARRAY['Hide a toy completely under a blanket and ask, “Where did it go?”']),
        ('Communication', 'Says “mama” and “dada” (can be non-specific)', 46, 60, ARRAY['Consistently refer to yourself and your partner by these names.', 'Show them pictures of you and say the names.']),
        ('Motor', 'Stands alone for a few seconds', 48, 64, ARRAY['When they pull to stand, help them find their balance and let go for a second.', 'Celebrate their attempts with lots of praise.']),
        ('Fine Motor', 'Puts objects into a container and takes them out', 49, 64, ARRAY['Provide a small bucket and some chunky blocks.', 'Show them how to drop things in and dump them out.']),
        ('Cognitive', 'Copies gestures you make (e.g., clapping, pointing)', 50, 64, ARRAY['Play clapping games like “Pat-a-Cake.”', 'Point to objects in books and around the room.']),
        ('Motor', 'Takes a few steps independently', 52, 70, ARRAY['Hold their hands and walk with them.', 'Sit on the floor a short distance away and encourage them to walk to you.']),
        ('Communication', 'Says one or two other words besides “mama” or “dada”', 54, 70, ARRAY['Name objects you see and use throughout the day.', 'When they point at something, say the word for it.']),
        ('Cognitive', 'Follows a simple one-step command without gestures (e.g., “Give me the ball”)', 56, 72, ARRAY['Use simple, clear language.', 'Make it a game: “Can you bring me your shoes?”']),
        ('Fine Motor', 'Scribbles with a crayon', 58, 72, ARRAY['Provide large, chunky crayons and big sheets of paper taped to the floor or high chair tray.']),
        ('Motor', 'Walks well without support', 60, 78, ARRAY['Go for short walks outside on safe, flat surfaces.', 'Play games that involve walking, like “Ring Around the Rosie.”']),
        ('Fine Motor', 'Builds a tower of 2-3 blocks', 62, 78, ARRAY['Use large, easy-to-stack blocks.', 'Build a tower yourself to show them how.']),
        ('Communication', 'Points to a body part when asked (e.g., “Where''s your nose?”)', 64, 80, ARRAY['Sing “Head, Shoulders, Knees, and Toes.”', 'Look in a mirror together and point to your features.']),
        ('Cognitive', 'Identifies one or two familiar objects in a picture book', 66, 80, ARRAY['Read board books with simple, clear pictures of objects they know.', 'Ask, “Where is the ball?” and guide their hand to point.']),
        ('Motor', 'Can run', 68, 85, ARRAY['Play chase in a safe, open area.', 'Encourage running games at the park.']),
        ('Fine Motor', 'Uses a spoon (may be messy)', 70, 85, ARRAY['Offer thick foods like yogurt or oatmeal that are easier to scoop.', 'Use a spoon with a short, chunky handle.']),
        ('Communication', 'Has a vocabulary of 10-20 words', 72, 90, ARRAY['Read to your child every day.', 'Talk constantly, even if it feels like a one-sided conversation.']),
        ('Cognitive', 'Engages in simple pretend play (e.g., feeding a doll)', 74, 90, ARRAY['Provide simple props like a toy phone, a doll, or a toy kitchen.', 'Pretend with them to model the behavior.']),
        ('Motor', 'Kicks a ball forward', 76, 95, ARRAY['Use a large, lightweight ball.', 'Show them how to kick it, then roll it to them to try.']),
        ('Fine Motor', 'Builds a tower of 4-6 blocks', 78, 95, ARRAY['Challenge them to build a tower “as tall as this cup.”', 'Use blocks of different shapes and sizes.']),
        ('Communication', 'Follows two-step commands (e.g., “Pick up your toy and put it in the box”)', 80, 100, ARRAY['Break down tasks into two simple steps.', 'Give praise after they complete both parts.']),
        ('Cognitive', 'Sorts objects by shape or color', 82, 100, ARRAY['Get sorting toys or use household items like different colored blocks or socks.', 'Start with just two colors or shapes.']),
        ('Motor', 'Walks up and down stairs holding on', 85, 105, ARRAY['Practice on a small step stool first.', 'Always supervise closely on stairs.']),
        ('Fine Motor', 'Turns pages of a board book one by one', 88, 105, ARRAY['Let them “help” you turn the pages during story time.', 'Choose sturdy board books that are easy for little hands to handle.']),
        ('Communication', 'Uses 2-3 word sentences (e.g., “More milk,” “Want ball”)', 90, 110, ARRAY['Expand on their phrases. If they say “Want ball,” you say, “You want the big red ball!”']),
        ('Social', 'Shows signs of empathy (e.g., comforts another child who is sad)', 92, 110, ARRAY['Label emotions for them: “He is sad because he fell down.”', 'Model empathetic behavior yourself.']),
        ('Motor', 'Jumps with both feet off the ground', 95, 115, ARRAY['Practice jumping like a frog.', 'Jump over a small line on the ground.']),
        ('Fine Motor', 'Draws a vertical line', 98, 115, ARRAY['Draw a line yourself and ask them to copy it.', 'Use different materials like chalk on the sidewalk or finger paint.']),
        ('Communication', 'Can name 5-10 familiar objects or pictures', 100, 120, ARRAY['Play “I Spy” with objects around the room.', 'Look through photo albums and name family members.']),
        ('Cognitive', 'Understands concepts of “one” and “all”', 102, 120, ARRAY['During snack time, say, “Here is *one* cracker. Now you can have them *all*.”']),
        ('Motor', 'Pedals a tricycle', 105, 125, ARRAY['Start with a balance bike to help them learn balance first.', 'Choose a tricycle that is the right size for them.']),
        ('Fine Motor', 'Unscrews a jar lid or turns a doorknob', 108, 125, ARRAY['Provide toys with knobs and dials.', 'Let them “help” you open a plastic jar.']),
        ('Communication', 'Uses pronouns like “I,” “me,” “you”', 110, 130, ARRAY['When they say, “Timmy wants cookie,” you can say, “*I* want a cookie.”']),
        ('Social', 'Plays cooperatively with other children for short periods', 112, 130, ARRAY['Arrange short playdates.', 'Provide toys that encourage sharing, like a large set of blocks.']),
        ('Motor', 'Catches a large ball with arms extended', 115, 135, ARRAY['Gently toss a large, soft ball to them from a short distance.']),
        ('Fine Motor', 'Draws a circle', 118, 135, ARRAY['Draw a smiley face and have them draw the head.', 'Trace around a cup.']),
        ('Communication', 'Asks “Why?” questions', 120, 140, ARRAY['Answer their questions simply and patiently, even if they ask the same one repeatedly.']),
        ('Cognitive', 'Understands basic concepts like big/small, up/down', 122, 140, ARRAY['Use these words in everyday conversation: “Let''s use the *big* cup.” “Look *up* at the airplane.”']),
        ('Motor', 'Hops on one foot for a few seconds', 125, 145, ARRAY['Play hopscotch.', 'Pretend to be flamingos or bunnies.']),
        ('Fine Motor', 'Cuts paper with child-safe scissors', 128, 145, ARRAY['Start by having them snip the edges of a piece of paper.', 'Draw thick lines for them to practice cutting along.']),
        ('Communication', 'Tells a simple story or recounts events of their day', 130, 150, ARRAY['Ask open-ended questions like, “What was the best part of your day?”']),
        ('Social', 'Shows increasing independence and may test boundaries', 132, 150, ARRAY['Offer simple choices to give them a sense of control (e.g., “Do you want the red shirt or the blue shirt?”).', 'Maintain consistent, predictable routines.']),
        ('Motor', 'Dresses and undresses self with minimal help', 135, 155, ARRAY['Choose easy-to-manage clothing like pants with elastic waists and oversized t-shirts.', 'Practice with doll clothes.']),
        ('Fine Motor', 'Draws a person with 2-4 body parts', 138, 155, ARRAY['Talk about the different parts of the body as you draw together.', 'Sing “Head, Shoulders, Knees, and Toes.”']),
        ('Communication', 'Can say their first and last name', 140, 160, ARRAY['Practice singing a little song with their full name in it.']),
        ('Cognitive', 'Understands the concept of counting and may know a few numbers', 142, 160, ARRAY['Count things in everyday life: stairs, crackers, toys.', 'Read counting books.']),
        ('Motor', 'Can skip', 145, 165, ARRAY['Break it down: “Step, hop, step, hop.”', 'Hold their hand while they practice.']),
        ('Fine Motor', 'Copies a cross shape (+)', 148, 165, ARRAY['Draw one and have them trace it, then try to draw their own next to it.']),
        ('Communication', 'Speaks in sentences of 5-6 words', 150, 170, ARRAY['Engage in conversations about their interests.', 'Read more complex storybooks.']),
        ('Social', 'Wants to please and be like friends', 152, 170, ARRAY['Acknowledge and praise positive social behaviors like sharing and taking turns.']),
        ('Motor', 'Can do a somersault', 155, 175, ARRAY['Practice on a soft surface like a carpeted floor or grass.', 'Show them how to tuck their chin to their chest.']),
        ('Fine Motor', 'Draws a person with at least 6 body parts', 158, 175, ARRAY['Ask them questions about their drawing: “What is this part? Where are the arms?”']),
        ('Communication', 'Understands and uses future tense (e.g., “We will go to the park tomorrow”)', 160, 180, ARRAY['Talk about upcoming plans and events.']),
        ('Cognitive', 'Can name at least four colors', 162, 180, ARRAY['Play “I Spy” with colors.', 'Point out colors in books and on clothing.']),
        ('Motor', 'Swings and climbs confidently', 165, 185, ARRAY['Visit a playground regularly.', 'Ensure the equipment is safe and age-appropriate.']),
        ('Fine Motor', 'Prints some letters of their name', 168, 185, ARRAY['Provide alphabet puzzles and magnets.', 'Write their name and have them trace the letters.']),
        ('Cognitive', 'Shows awareness of past and future (e.g., “We went to the park yesterday,” “We will see Grandma tomorrow”)', 169, 185, ARRAY['Use a simple calendar to mark special events.', 'Talk about the plan for the day each morning.']),
        ('Fine Motor', 'Can complete a 10-12 piece puzzle', 170, 190, ARRAY['Choose puzzles with a clear picture and distinct shapes.', 'Work on it together as a team.']),
        ('Fine Motor', 'Draws a square', 171, 190, ARRAY['Practice drawing “windows” on a picture of a house.', 'Use your finger to trace a square shape on their back.']),
        ('Motor', 'Balances on one foot for 3-5 seconds', 172, 190, ARRAY['Play “statue” or see who can stand like a flamingo the longest.']),
        ('Social', 'Understands and follows rules in simple group games like “Duck, Duck, Goose”', 173, 190, ARRAY['Play these games as a family first to teach the rules in a low-pressure environment.']),
        ('Communication', 'Correctly uses “he” and “she”', 174, 185, ARRAY['When reading books, point out the characters.', '“Look, *he* is running. *She* is climbing a tree.”']),
        ('Cognitive', 'Can count 5-10 objects with one-to-one correspondence (touches each object as they say the number)', 175, 195, ARRAY['Count snacks as you put them on their plate.', 'Count the steps as you walk up to the house.']),
        ('Social/Cognitive', 'Relates to and plays with an imaginary friend', 176, -1, ARRAY['This is a normal and healthy sign of a strong imagination.', 'Show interest and play along when invited.']),
        ('Communication', 'Can say what they did during their day in sequence', 177, 190, ARRAY['Ask specific questions: “What did you do after you had your snack?”', '“Who did you play with outside?”']),
        ('Social', 'Negotiates solutions to conflicts (e.g., “I''ll have it for two minutes, then you can”)', 178, 195, ARRAY['When conflicts arise with a friend, act as a “coach” instead of a “referee.”', 'Help them voice their feelings and brainstorm solutions.']),
        ('Cognitive', 'Recognizes several letters, especially those in their own name', 179, 195, ARRAY['Use alphabet puzzles and magnetic letters.', 'Point out the letters of their name on signs and in books.']),
        ('Motor', 'Catches a bounced ball with their hands (not trapping against their body)', 180, 195, ARRAY['Stand close and gently bounce a large, lightweight ball to them.', 'As they improve, you can stand farther away.'])
), inserted_milestones AS (
    INSERT INTO public.milestones (category, title, first_noticed_weeks, worry_after_weeks)
    SELECT category, title, first_noticed_weeks, worry_after_weeks FROM milestone_data
    RETURNING id, title
)
INSERT INTO public.milestone_activities (milestone_id, description)
SELECT im.id, unnest(md.activities)
FROM milestone_data md
JOIN inserted_milestones im ON md.title = im.title;
